@hostname = localhost

@port = 5101

@host = https://{{hostname}}:{{port}}

@contentType = application/json

###

GET {{host}}/api/users 

###

GET {{host}}/api/users/1

###

DELETE {{host}}/api/users/0

###

POST {{host}}/api/users
Content-Type: {{contentType}}

{
    "FirstName": Brian, "LastName": Jackson, "id": 22
}

###

PUT {{host}}/api/users
Content-Type: {{contentType}}

{
    "FirstName": Jared, "LastName": Bolender, "id": 20
}