# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - BrianJacksonSecretSanta(Production), Build and deploy DotnetCore app

on:
  push:
    branches:
      - Assignment9

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Get Directory
      run: pwd

    - name: Run Npm Build
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: |
        npm install
        npm run build:prod

    - name: Run API
      working-directory: ./SecretSanta/src/SecretSanta.Api/
      run: dotnet run

    - name: Restore dependencies
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: BrianJacksonSecretSanta
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9B82128CA10D440F89C0A937671D6471 }}
        package: ${{env.DOTNET_ROOT}}/myapp

